on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  stable-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup/
            target/
          key: stable-x86_64-unknown-linux-gnu-${{ hashFiles('**/Cargo.lock') }}

      - if: steps.cache-cargo.outputs.cache-hit != 'true'
        name: "Install tools"
        run: |
          rustup set profile minimal
          rustup install stable
          rustup override set stable
          rustup component add rustfmt clippy

      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
        env:
          RUSTFLAGS: "-C target-cpu=native"
      - run: cargo test
        env:
          RUSTFLAGS: "-C target-cpu=native"

  stable-aarch64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup/
            target/
          key: stable-aarch64-unknown-linux-gnu-${{ hashFiles('**/Cargo.lock') }}

      - if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: |
          rustup set profile minimal
          rustup install stable
          rustup target add aarch64-unknown-linux-gnu
          rustup toolchain install --target=aarch64-unknown-linux-gnu stable
          rustup component add --toolchain stable clippy

      - run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu qemu-user-static

      - run: cargo clippy --target aarch64-unknown-linux-gnu -- -D warnings
        env:
          RUSTFLAGS: "-C target-cpu=cortex-x2"
      - run: cargo test --target aarch64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-C target-cpu=cortex-x2"
