on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  amd64-linux-stable:
    name: amd64-linux-stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: Run cargo build --release
        with:
          command: build
          args: --target x86_64-unknown-linux-gnu --release
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      - name: Create a tarball
        run: cp target/release/ge . && tar cf ge ge-amd64-linux.tar.gz && rm ge
      - uses: svenstaro/upload-release-action@v2
        name: Upload binaries to release
        with:
          file: ge-amd64-linux.tar.gz

  aarch64-linux-stable:
    name: aarch64-linux-stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        name: Run cargo build --release
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --release
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      - name: Create a tarball
        run: cp target/aarch64-unknown-linux-gnu/release/ge . && tar cf ge ge-aarch64-linux.tar.gz && rm ge
      - uses: svenstaro/upload-release-action@v2
        name: Upload binaries to release
        with:
          file: ge-aarch64-linux.tar.gz
